name: Scrape Reddit Top (Last 7 Days)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * *"
    - cron: "50 12 * * FRI"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -V
          pip install -r requirements.txt

      - name: Run scraper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          LIMIT_PER_SUB: "20"
          SLEEP_BETWEEN_CALLS: "1.6"
          COMMENTS_LIMIT: "50"
        run: |
          python scraper.py
          echo "List data dir after scrape:"
          ls -la data || true

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update scraped feed" || echo "No changes to commit"
          git push

      # ---------- NEW: set a flag instead of using secrets.* in if: ----------
      - name: Detect Drive secrets
        run: |
          echo "HAS_GDRIVE=${{ (secrets.GCP_SA_KEY != '' && secrets.GDRIVE_FOLDER_ID != '') && 'true' || 'false' }}" >> $GITHUB_ENV
          echo "HAS_GDRIVE is set to: $HAS_GDRIVE"

      - name: Install Google Drive deps
        if: env.HAS_GDRIVE == 'true'
        run: |
          pip install google-api-python-client>=2.137.0 google-auth>=2.33.0 google-auth-httplib2>=0.2.0

      - name: Upload to Google Drive
        env:
          GDRIVE_CLIENT_SECRET_JSON: ${{ secrets.GDRIVE_CLIENT_SECRET_JSON }}
          GDRIVE_TOKEN_JSON: ${{ secrets.GDRIVE_TOKEN_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python scripts/upload_to_drive.py
